### ISSUE TITLE
[Feature Request] Add timeout for effect of votes on comments

### ISSUE THREAD

**Issue by CoolDevelopment** [LemmyNet/lemmy#3104]
- [X] Did you check to see if this issue already exists?
- I searched for "is:issue timeout vote" and did not find any similar idea
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support.
- [] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

**Describe the feature request below**
Hey guys,

I want to suggest an option for creators of posts to set a timeout with following consequences:

- Until timeout is reached, the amount of votes of any comment is not available to users.
- As consequence, sorting of comments by amount of votes is not possible either

The effect I hope for by this timeout, that the effect of biasing opinion based on other peoples opinions is reduced, priming the comment section for a more diverse discussion posterior to the timeout.
A bad outcome may of course be "too diverse" discussion, because of more complicated moderation prior to the timeout.

**Comment by dessalines** [comment]
You can currently hide vote scores in your user settings, which would be the best option to not introduce vote bias (if you choose).
