### ISSUE TITLE
Lemmy server Health Bar so users know if their server is sustainably funded

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy#3793]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Is your proposal related to a problem?

Servers cost money every month and its hard for users to know if their server has enough funds to be sustainable in the long run. 

### Describe the solution you'd like.

Having a native ui for users to see how much money the server bill is and how much funds are currently being donated will help ensure server stay sustainably funded. We can have something akin to a Health Bar similar to how reddit had their Gold bar before they decided to stop being as transparent and focus on infinite growth for their venture capitalists demands 

### Describe alternatives you've considered.

![873c56efbfe242b4aa752709d74efd45](https://github.com/LemmyNet/lemmy/assets/114287507/9f0cb0f1-cc8d-46c6-9474-9816b43be741)

**Comment by laurencedawson** [comment]
It would be great if this was also part of the site json along with a link to a page on how to donate to the instance.

Something like this:

```
{
    "donation_link" : "https://example.com",
    "donation_goal_achieved" : 89.8
}
```


That way apps can easily display this data too and allow users to donate.

**Comment by Nutomic** [comment]
Should Lemmy add support to query Patreon, Liberapay and dozens of other platforms for this information? Thats completely unrealistic, instead you can embed an external image which shows this info.
