### ISSUE TITLE
Federation missing features

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy#647]
We now have basic, working federation, but a lot of things are still missing. Some of these issues should be quite easy to solve, and we would be happy about contributions. Just get in touch first so we can coordinate things.

### Features
- [x] use same url for apub id / apub json / html
- [x] federate comments (create, update)
- [x] federate votes
- [x] Add community id to the actors of accept.
- [x] The `to` field on accept is wrong, its sending it to the wrong actor, a community should be sending accept to the user's inbox.
- [x] Add an ap_id to the communityfollower table. Seems weird that every little thing needs an id, but it do.
- [x] implement deleting community, post, comment
- [x] Add [Undo](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-undo) actions for things like delete, remove, upvote, downvote, follow
- [x] [Allow mods to remove posts/comments](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-remove)
- [x] federate post nsfw, locked
- [x] federate community category, nsfw
- [x] Private messages
- [x] add comment endpoint
- [x] Federated mentions #681 
- [x] User icons, post thumbnails
- [x] federate post::embed 
- [x] Community updates: make sure nsfw and sidebar changes propagate
  - nsfw is updated fine after update interval
  - description change is not propagated
- [x] federate post::stickied, 
- [x] Fetch all inreplyto objects: #694 
- [x] Proper CommunityFollower forwarding: #662 
- [x] In all the receives, in addition the the signature verify, do a check to make sure they are actually allowed to do the action.

### Security and Maintenance
- [x] Ensure urls start with https:// and verify attributedTo, ID and pubkey URLs are from the same domain/actor
- [x] limit number of additional fetches for each activtypub object or activity (only necessary for outbox, other than that we arent doing recursive/list fetching)
- [x] maybe write a single function that recursively checks all urls in an object ([implemented in activitystreams](https://docs.rs/activitystreams/0.7.0-alpha.4/activitystreams/base/trait.BaseExt.html#method.id))
- [x] get rid of unwrap() in apub code (probably best to use `Option::ok_or()`)
- [ ] find out what kinds of security checks are done by mastodon, pleroma etc
- [ ] apply bans, slur filters, length checks etc to posts coming in over activitypub
- [ ] go through all the TODO and see if there is anything important
- [x] implement instance blocklist
- [x] remove tags like <script> from federated html before rendering it (eg in embeds)
- [x] Migrate to asonix' [new activitystreams library](https://git.asonix.dog/asonix/activitystreams-sketch)
- [x] make sure private messages can only retrieved by ID if the client is authenticated (private messages dont have any http route)
- [ ] setup fuzzing for activitypub inbox and other endpoints
- [ ] maybe create an instance with open federation and ask people to attack it
- [x] remove usage of `id_unchecked()`
- [ ] add rate limit for activitypub inbox, specifically to limit requests from instances that cause many errors
- [x] setup security@lemmy.ml address with pgp
- [x] Make sure moderation activities NOT on the hosting instance, aren't pushed / received, or are ignored.

## Frontend
- [x] properly handle following remote communities. #650 
- [x] Add working non-federated community linking (IE `/community/id`)
- [x] make search for apub id (community/user/post) easier
- [x] dont clear search box after clicking "search" (helps when searching for apub id and entering it wrong)
- [x] properly handle communities with identical names (by putting `/c/main@domain` in the url for remote communities)
- [x] remove options like "make mod" or "make admin" for remote users
- [x] Create a "linked instances" page.

**Comment by Nutomic** [comment]
If you want to help with development, our [documentation](https://enterprise.lemmy.ml/docs/contributing_federation_development.html) has instructions for creating a local federation test setup.

**Comment by trymeouteh** [comment]
Private messaging will be cool but should not be added until all else is done. If you do add private messaging you should look at minds.com since they are working on a federated platform and E2EE messaging. There is also OpenPGP which can be used for encrypted messages between users from different instances.

**Comment by dessalines** [comment]
Private messaging is added to the federation test instances, so that's done ;)

We still have a lot of things on the list to do tho, I'm working on federated mentions which is pretty difficult.

**Comment by stemid** [comment]
Unfortunately I've never used Rust or Typescript but may I suggest ActivityPub relay support? I run a mastodon instance and using just a couple AP relays my public timeline is a lot more active than without them.

**Comment by Nutomic** [comment]
@stemid I dont think there is anything we need to do to support relays. Afaik the relay just needs to be compatible with the ActivityPub variant used by Lemmy. If there is anything we need to do, please open a separate issue.

**Comment by stemid** [comment]
@Nutomic ok I'm planning on setting up my own lemmy instance so I'll take a look at how it works. As far as I know AP relays can have different routes for different implementations. Like for example Mastodon posts to /inbox and Pleroma posts to /actor. But since mastodon allows you to enter a full URL of relay this probably isn't a constant.

And you still need to subscribe to the relay, something Mastodon has a whole UI section for.

**Comment by grravity** [comment]
Few questions:

First, would there be any plans to allow users to merge accounts between instances? But in theory they'd be seperated? For example, banning one account that is merged to another, would only apply the ban to that account, not both merged accounts. I think this merging would be a great QoL feature if implemented right. Meaning everything would be able to be seperated, but would allow users to see all their posts, comments, etc. seperate from one another.
Community mods would only be able to see the account that is in relation to their instance, so if one of the users merged accounts only Federates with that community, but the other doesn't, the mod of that community cannot see the account and post history, etc. of the account that does not Federate with that instance. This would be bad if they could see both, as they may make judgements off of their post history as a whole, rather than their behavior in the specific community they're moderating. So a separation would be needed, but I think the ability to merge accounts would be very cool if possible and done right.

Secondly, is there any plans to incorporate some type of blockchain system, P2P, maybe IPFS? Idk. But in which all posts work through this system redudantly? Similar to how LBRY works, this would be absolutely amazing for archival purposes alongside the already self-hosted instances. But currently, if you think about it, if an instance host goes down, all the communities go with it. The blockchain/P2P system would essentially act as redundant archive of everything so stuff is never truly lost and even stuff that gets deleted actually doesn't get deleted, it just gets hidden from view on the instances, but can live on in the blockchain. This would be major for instances that start getting touchy with censorship. There's a reason people upload Twitter screenshots up to archival sites, etc. I think this would be a major benefit if possible, although I am not entirely sure the technicalities as to how it would or should work. I just want to throw this out there as I think it is extremely important to preserve and archive stuff.

Third, I am curious if we have an instance list yet? And if we have a goal or a rough ETA as to when the Federation of Lemmy may be complete?

**Comment by poVoq** [comment]
As for the first point: That is very similar to what "nomadic identities" from Zap/Hubzilla does (incl. channel cloning). I think the original developer of both recently posted a guide on how it works also with ActivityPub in Zap despite the AP protocol not integrating it originally. At least with the Zot protocol (native ActivityPub alternative) in Hubzilla and Zap it works really nicely.

**Comment by Nutomic** [comment]
This is finished, except for a few items which are too vague or which we decided not to do (or do differently).

**Comment by arjenpdevries** [comment]
Should the main website still say federation is incomplete/untested?

**Comment by Nutomic** [comment]
@arjenpdevries No it shouldnt. Would you mind changing that?
